- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
    - python-apt

- name: Install docker key
  apt_key:
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Install docker repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    state: present

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: Install docker-engine
  apt: pkg={{ item }} state=present
  with_items:
    - docker-engine

- name: Install pip packages
  pip: name=docker-py version=1.4.0 state=present